management:
  endpoints:
    web:
      exposure:
        include: "*"

#setting up mysql connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_db?createDatabaseIfNotExist=true
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


