server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nisal-kumara/krish-lp-training/tree/master/MicroService_Practices/externalized-config-server
          search-paths:
            - 'service-config/*service'

